server:
  port: 8082
  session: 
    timeout: 256200
logging: 
  config: classpath:logback-boot.xml
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://47.94.198.47:3306/lpublicplay
    username: root
    password: 123456
  jpa:
    hibernate:
      ddl-auto: update
      naming:
        strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: true
  redis:
    host: 47.94.198.47
    port: 6379
    timeout: 5000
    pool:
      max-active: 8
      min-idle: 0
      max-idle: 8
      max-wait: -1
    password: 
  application:
    name: spring-boot-redis
